[package]
name = "switch_windows_theme"
version = "1.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }
winreg = "0.52.0"

[build-dependencies]
embed-resource = "2.4.3"
